package com.mygdx.engine.gamelogic.message;

public enum MessageData {
	SELECTEDDISPLAY, FULLSCREENON, VSYNCON, SAVEON, DISPLAY,
	GOLD, WOOD, FOOD, STONE, CURRENTPOPULATION, MAXPOPULATION,
	NAME, OWNER, HITPOINTS, CURRENTHITPOINTS, ATTACKPOWER, ATTACKRATE, RANGE, ARMOR, OWNERNAME,
	CURRENTRESOURCEAMOUNT, MAXRESOURCEAMOUNT,
	RAYDIRECTIONX, RAYDIRECTIONY, RAYDIRECTIONZ, RAYORIGINX, RAYORIGINY, RAYORIGINZ,
	RESOURCETYPE, RESOURCEAMOUNT, RESOURCERESET,
	BUTTON0, BUTTON1, BUTTON2, BUTTON3, BUTTON4, BUTTON5, BUTTON6, BUTTON7, BUTTON8, 
	BUTTON9, BUTTON10, BUTTON11, BUTTON12, BUTTON13, BUTTON14, BUTTON15, BUTTON16,
	CREATEVILLAGER, CURRENTPROCESSING, PROCESSINGCOUNTER, QUEUE
	
}
