package com.mygdx.engine.gamelogic.message;

public enum MessageType {
	PLAY, OPTIONS, EXIT,
	BACK, DISPLAY, CURRENTDISPLAY, FULLSCREEN, VSYNC, RESET, ASK, APPLY, SAVE,
	SELECTRAY, MOVERAY, NOTE, NAME, UNSELECTED, SELECTEDDATA, PLAYERDATA, BUTTONCLICK, 
	ACTIVECASTING, ACTIVECASTINGON, ACTIVECASTINGOFF,
	CREATEVILLAGER, CREATEBUILDINGTOWNCENTER, CREATEBUILDINGMININGCAMP
}
